import PDFDocument from 'pdfkit';

export const PDFExporter = {
    async generateBuffer(dataStore: Record<string, any[]>): Promise<Buffer> {
        return new Promise((resolve, reject) => {
            try {
                const doc = new PDFDocument({ margin: 50 });
                const buffers: Buffer[] = [];

                doc.on('data', buffers.push.bind(buffers));
                doc.on('end', () => resolve(Buffer.concat(buffers)));

                // Title
                doc.fontSize(20).text('Synthetic Data Generation Report', { align: 'center' });
                doc.moveDown(2);

                // Summary details
                const tables = Object.keys(dataStore);
                doc.fontSize(14).text(`Total Tables Generated: ${tables.length}`);
                doc.moveDown();

                tables.forEach(tableName => {
                    const rows = dataStore[tableName];
                    doc.fontSize(12).text(`Table: ${tableName} -> ${rows.length} rows`);
                });

                doc.moveDown(2);
                doc.fillColor('grey').fontSize(10).text('This report summarizes the data generated by the MERN Synthetic Data Generator Platform.', { align: 'center' });

                doc.end();
            } catch (err) {
                reject(err);
            }
        });
    }
};
